'use strict';
/* английские тексты таблиц data.js — наложение по id (см. js/i18n.js). Новая строка в data.js — сразу сюда */
const I18N_EN={
  HEROES:{
    dob:{name:"Dobrynya Nikitich",title:"Dragon Slayer",perk:"+10% damage",
      dar:{name:"Battle Cry",about:"Shockwave: damages and knocks back monsters"}},
    ale:{name:"Alyosha Popovich",title:"Sly Archer",perk:"+12% speed",
      dar:{name:"Daredevil Dash",about:"Dash with 2 s of invulnerability + a volley of arrows all around"}},
    ily:{name:"Ilya Muromets",title:"Eldest Bogatyr",perk:"+30% health, +1 armor",
      dar:{name:"Ground Slam",about:"Stuns all monsters around you for 2.5 s"}},
    vas:{name:"Vasilisa the Wise",title:"Enchantress",perk:"−10% cooldown, +10% area",
      dar:{name:"Great Wisdom",about:"Pulls in all gems and heals 15% health"}},
    sad:{name:"Sadko",title:"Minstrel Merchant",perk:"+20% XP, +10% area",
      dar:{name:"Sadko's Song",about:"Slows every monster on screen for 5 s"}},
    mik:{name:"Mikula Selyaninovich",title:"Mighty Plowman",perk:"+50% health, +2 armor, −10% speed",
      dar:{name:"The Furrow",about:"Plows a long furrow: huge damage in a line"}},
    vol:{name:"Volga Svyatoslavich",title:"Shapeshifter Mage",perk:"+20% speed, −10% cooldown",
      dar:{name:"Wolf Form",about:"5 s as a wolf: faster, bites all in your path"}},
    mar:{name:"Marya Morevna",title:"Warrior Princess",perk:"+15% damage, +10% area",
      dar:{name:"Flying Swords",about:"6 swords circle you for 6 s"}},
    iva:{name:"Ivan the Fool",title:"Lucky Duck",perk:"+50% luck, +20% gold",
      dar:{name:"Fool's Luck",about:"Pot luck: a chest, gold rain or full health"}}
  },
  RANKS:{0:"Recruit",1:"Guardsman",2:"Knight",3:"Warlord",4:"Bogatyr",5:"Legendary"},
  WEAPONS:{
    sword:{name:"Kladenets Sword",about:"Slashes everyone in front of you",
      up:["","+25% damage, wider swing","Also slashes behind you","+damage, faster","Huge swing"],
      evo:{name:"Self-Swinging Sword",about:"Slashes all around you, huge damage"}},
    bow:{name:"Alyosha's Bow",about:"Shoots the nearest foe",
      up:["","+1 arrow","Arrows pierce 2 foes","+1 arrow","+1 arrow, +damage"],
      evo:{name:"Thunder Arrows",about:"6 arrows that pierce everything"}},
    mace:{name:"Mace",about:"Spins around the hero",
      up:["","+damage, wider circle","+1 mace","+damage, wider circle","+1 mace, +damage"],
      evo:{name:"Heavyweight Maces",about:"6 huge maces that fling monsters away"}},
    fire:{name:"Firebird Feather",about:"Fire homes in on foes and explodes",
      up:["","+damage, bigger blast","+1 flame","Faster, bigger blast","+1 flame, +damage"],
      evo:{name:"Firebird Flock",about:"5 fiery birds, huge explosions"}},
    gusli:{name:"Self-Playing Gusli",about:"Music hits and slows everyone nearby",
      up:["","+damage, wider","+damage","Wider, stronger","+damage, wider"],
      evo:{name:"Ringing Gusli",about:"A huge circle of music that heals you"}},
    perun:{name:"Perun's Lightning",about:"Strikes random foes from the sky",
      up:["","+1 bolt","+damage, faster","+1 bolt","+1 bolt, +damage"],
      evo:{name:"Perun's Wrath",about:"6 bolts, each jumps to 3 more foes"}},
    kolo:{name:"Kolobok",about:"Rolls, bounces and squashes everyone",
      up:["","Rolls longer, +damage","+1 kolobok","+damage, longer","+1 kolobok"],
      evo:{name:"Kolobok Bogatyrs",about:"4 giant koloboks roll for 6 seconds"}},
    axe:{name:"Boomerang Axe",about:"Flies out and comes back",
      up:["","+damage, faster","+1 axe","+damage, faster","+1 axe"],
      evo:{name:"Whirlwind Axes",about:"6 axes fly out in all directions"}},
    water:{name:"Dead Water",about:"Puddles that burn monsters",
      up:["","+damage, bigger puddle","+1 flask","+damage, faster","+1 flask, bigger"],
      evo:{name:"Living & Dead Water",about:"Huge puddles burn monsters and heal you"}}
  },
  PASSIVES:{
    apple:{name:"Rejuvenating Apple",about:"+15% health"},
    mail:{name:"Chainmail",about:"+1 armor"},
    boots:{name:"Seven-League Boots",about:"+8% speed"},
    ball:{name:"Magic Yarn Ball",about:"+25% gem magnet"},
    ring:{name:"Ring of Might",about:"+10% damage"},
    livew:{name:"Living Water",about:"+0.3 health per second"},
    cloth:{name:"Magic Tablecloth",about:"+10% XP"},
    comb:{name:"Magic Comb",about:"+10% attack area"},
    amulet:{name:"Lucky Charm",about:"−7% cooldown"},
    quiver:{name:"Quiver",about:"+1 projectile for every weapon"}
  },
  EN:{
    muh:{n:"Toadstool"},bat:{n:"Bat"},wolf:{n:"Wolf"},lesh:{n:"Leshy"},piy:{n:"Leech"},kik:{n:"Kikimora"},
    ogon:{n:"Will-o'-Wisp"},vod:{n:"Vodyanoy"},voron:{n:"Raven"},skel:{n:"Skeleton"},upyr:{n:"Upyr"},
    idol:{n:"Idolishche"},prizr:{n:"Ghost"},koldun:{n:"Sorcerer"},rycar:{n:"Bone Knight"},kot:{n:"Black Cat"},
    wolf_i:{n:"Ice Wolf"},ledyan:{n:"Ice Spirit"},snow:{n:"Snowman"},shatun:{n:"Grumpy Bear"},
    ryba:{n:"Toothy Fish"},rak:{n:"Hermit Crab"},rusalka:{n:"Rusalka"},vod_s:{n:"Sea Vodyanoy"},
    chert:{n:"Imp"},ognev:{n:"Fire Sprite"},skel_f:{n:"Fire Skeleton"},idol_f:{n:"Fire Idol"},
    solo:{n:"Nightingale the Robber"},yaga:{n:"Baba Yaga"},gory:{n:"Zmey Gorynych"},kosh:{n:"Koschei the Deathless"},
    karach:{n:"Karachun"},morcar:{n:"Sea Tsar"},tugar:{n:"Tugarin Zmey"},liho:{n:"Likho One-Eye"},
    egg:{n:"Egg with the Needle"},
    pen:{n:"Stump"},kol:{n:"Log"}
  },
  FINDS:[
    {n:"Burst-Grass!",s:"Small monsters on screen: gone with the wind"},
    {n:"Sleep-Grass!",s:"Monsters fall asleep for 5 seconds"},
    {n:"Magic Yarn Ball!",s:"All gems fly to you"},
    {n:"Karavai Loaf!",s:"+50% health"},
    {n:"Pot of Gold!",s:"Gold flies straight into your pocket"}
  ],
  CH:{ /* M2: по СЛОТУ (ключ = номер слота, как в CH/S.done); главы тем 8–32 переводятся в своих файлах (поле en главы → tr) */
    0:{name:"Deep Dark Forest",sub:"Where Leshy roams and wolves howl"},
    1:{name:"Deadly Swamp",sub:"Kikimoras giggle, Vodyanoy gurgles"},
    2:{name:"Wild Steppe",sub:"Ravens circle over burial mounds"},
    3:{name:"Koschei's Kingdom",sub:"They pine over gold and glow in the dark"},
    4:{name:"Frost Mountains",sub:"Snowmen throw, bears won't sleep"},
    5:{name:"Sea Kingdom",sub:"Crabs back off, rusalkas sing"},
    6:{name:"Land of Fire",sub:"Imps dance, the ground burns"},
    7:{name:"Thrice-Nine Kingdom",sub:"Likho never sleeps: one eye is watching"}
  },
  FORGE:{
    hp:{name:"Health",per:"+10% health"},
    might:{name:"Might",per:"+6% damage"},
    armor:{name:"Armor",per:"+1 armor"},
    spd:{name:"Speed",per:"+4% speed"},
    magnet:{name:"Magnet",per:"+20% pickup range"},
    cd:{name:"Cooldown",per:"−4% cooldown"},
    xp:{name:"Wits",per:"+6% XP"},
    luck:{name:"Luck",per:"+15% gold, chests and pirozhki"},
    gold:{name:"Greed",per:"+10% gold"}
  },
  BLD:{
    forge:{name:"Forge",about:"Permanent upgrades for heroes and weapons"},
    mill:{name:"Mill",about:"Opens the Treasury: +15 gold per hour offline"},
    altar:{name:"Shrine",about:"+1 card reroll per run"},
    barn:{name:"Barn",about:"+15% gold, Treasury holds +1.5 h"},
    tower:{name:"Watchtower",about:"+10% XP"},
    well:{name:"Well of Living Water",about:"+0.3 health per second"},
    hut:{name:"Wise Woman's Hut",about:"Gets you back on your feet once per run"},
    fair:{name:"Fair",about:"Treasury fills 25% faster"},
    tavern:{name:"Tavern",about:"4 cards to choose from instead of 3"}
  },
  PH:{
    lvl:["Power surging!","Oh, I feel mighty!","Brace yourselves!","Swing away, arm!","Bogatyr power!"],
    low:["Oof, that hurts…","Where's my pie?","Not today!","You won't get me!"],
    chest:["What a treasure!","A chest! Dibs!"],
    pie:["Babushka's pirozhki!","Cabbage filling! Yum!"],
    evo:["Now THAT's power!","Whoa, gorgeous!","Now watch out!"],
    en:{muh:["Don't eat me!","I'm poisonous!"],lesh:["Hello-o-o!","Get lost!"],kik:["Hee-hee-hee!","Tickle tickle!"],
      wolf:["Grrr!","Snap snap!"],vod:["Blub!","I'll drown you!"],skel:["My bones ache…","Clatter!"],
      upyr:["Just one bite!","Chomp!"],prizr:["Ooo-ooo!","Boo!"],koldun:["I'll hex you!"],
      idol:["I'll crush you!"],voron:["Caw!"],rycar:["Surrender!"],kot:["Meow!","Hsss!"],
      wolf_i:["Ooo, it's cold!"],snow:["Catch a snowball!","Hands off my carrot!"],
      shatun:["Who woke me up?!","I was sleeping!"],ledyan:["I'll freeze you!"],
      rak:["Snip-snap!","I walk backwards!"],rusalka:["La-la-la!","Come for a swim!"],ryba:["Gotcha!"],
      vod_s:["Blub-blub!"],chert:["Hee-hee, I'll singe you!","Horns and hooves!"],ognev:["So hot!"],
      skel_f:["Seeing sparks!"],idol_f:["I'll melt you!"]},
    boss:{
      solo:{intro:"One whistle and you're done!",lines:["Fweeeet!","Out of my way!","This is MY forest!"]},
      yaga:{intro:"Fee-fi-fo, I smell a hero!",lines:["Into the oven with you!","Kitties, sic 'em!","Mortar, full speed!"]},
      gory:{intro:"Three heads are better than one!",lines:["Got a fire extinguisher?","One head is good…","…but three is hot!"]},
      kosh:{intro:"I pine over gold, and I laugh at you!",lines:["I'm deathless, you know!","Mwa-ha-ha!"],
        egg:"My death is in the egg! Oops… why did I say that?"},
      karach:{intro:"I'll chill you, I'll freeze you, no warm stove for you!",lines:["Cold, bogatyr?","Put a coat on!","You'll be an icicle!"]},
      morcar:{intro:"Who dares enter my kingdom?",lines:["Crabs, attack!","Here comes a wave!","Have some trident!"]},
      tugar:{intro:"I'm Tugarin! I'll eat you whole!",lines:["Ha, too hot?","Sizzle-zzle!","Imps, follow me!"]},
      liho:{intro:"Let sleeping Likho lie…",lines:["I see you!","You can't hide from my eye!","There's only one Likho!"]}
    },
    win:["Dark Folk defeated!","Glory to the bogatyr!"],
    start:["Look out, monsters!","Time to sort you all out!","Just a little stroll!","Who invaded Rus uninvited?","Mom packed pirozhki. I got this!"],
    card:["That'll come in handy!","Ooh, new gear!","I'll take it! Wrap it up.","Fixes a wardrobe AND Koschei.","Always wanted one!","Babushka would approve."]
  },
  QUESTS:{
    kills:{t:"Defeat {n} monsters"},
    boss:{t:"Defeat bosses: {n}"},
    time:{t:"Survive {n} min in one run"},
    gold:{t:"Collect {n} gold in runs"},
    chest:{t:"Open {n} chests"},
    lvl:{t:"Reach level {n} in one run"},
    runs:{t:"Go on {n} runs"},
    dar:{t:"Use your hero's Power {n} times"},
    evo:{t:"Evolve a weapon"},
    endless:{t:"Survive {n} min in Endless Battle"},
    drun:{t:"Complete the Daily Run"}
  },
  SKINS:{
    gold:{name:"Golden Knight"},black:{name:"Black Warlord"},forest:{name:"Forest Archer"},jester:{name:"Skomorokh Jester"},
    fire:{name:"Fire Bogatyr"},snow:{name:"Snow Bogatyr"},swan:{name:"Swan Princess"},night:{name:"Night Enchantress"},
    sea:{name:"Seafarer"},field:{name:"Golden Field"},white:{name:"White Wolf"},dawn:{name:"Dawn Warrior"},
    tsar:{name:"Ivan Tsarevich"},merch:{name:"Overseas Merchant"},autumn:{name:"Autumn Harvest"},firew:{name:"Fire Wolf"},
    snowq:{name:"Snow Queen"},firebird:{name:"Firebird Catcher"},
    maslen:{name:"Maslenitsa"},newyear:{name:"New Year"},kupala:{name:"Kupala Night"}
  },
  CURSES:{0:"No curse",1:"Curse I",2:"Curse II",3:"Curse III",4:"Curse IV",5:"Curse V"},
  ACH:{
    k100:{name:"Off to a Start",about:"Defeat 100 monsters"},
    k1k:{name:"Terror of the Woods",about:"Defeat 1,000 monsters"},
    k10k:{name:"Exterminator",about:"Defeat 10,000 monsters"},
    k50k:{name:"Bane of the Dark Folk",about:"Defeat 50,000 monsters"},
    k200k:{name:"Legend of Rus",about:"Defeat 200,000 monsters"},
    b_solo:{name:"Nightingale Caged",about:"Defeat Nightingale the Robber"},
    b_yaga:{name:"Not the Oven!",about:"Defeat Baba Yaga"},
    b_gory:{name:"Three Heads Off",about:"Defeat Zmey Gorynych"},
    b_kosh:{name:"Needle Snapped",about:"Defeat Koschei the Deathless"},
    b_karach:{name:"The Thaw",about:"Defeat Karachun"},
    b_morcar:{name:"Lord of the Waters",about:"Defeat the Sea Tsar"},
    b_tugar:{name:"Firefighter",about:"Defeat Tugarin Zmey"},
    b_liho:{name:"Don't Wake Likho",about:"Defeat Likho One-Eye"},
    all8:{name:"Liberator of Rus",about:"Free all 8 lands"},
    r10:{name:"On the Road",about:"Go on 10 runs"},
    r50:{name:"Seasoned",about:"Go on 50 runs"},
    r100:{name:"A Hundred Roads",about:"Go on 100 runs"},
    l30:{name:"Battle-Hardened",about:"Reach level 30 in one run"},
    l50:{name:"Invincible",about:"Reach level 50 in one run"},
    e1:{name:"Wonder Weapon",about:"Evolve your first weapon"},
    e9:{name:"Evolution Master",about:"Evolve all 9 weapons"},
    end10:{name:"Steadfast",about:"Survive 6 minutes in Endless Battle"},
    end20:{name:"Unbending",about:"Survive 12 minutes in Endless Battle"},
    end30:{name:"Eternal Guardian",about:"Survive 18 minutes in Endless Battle"},
    one:{name:"One and Only",about:"Win a chapter with just one weapon"},
    nopas:{name:"No Charms",about:"Win a chapter without taking a single charm"},
    tough:{name:"Unbreakable",about:"Win chapter 4 or later taking 5 hits or fewer"},
    ch5:{name:"Lucky Streak",about:"Open 5 chests in one run"},
    g1k:{name:"Full Purse",about:"Bring home 1,000 gold from one run"},
    vil:{name:"Village Builder",about:"Build every building in the Village"},
    frg:{name:"Master Smith",about:"Get 30 levels in the Forge"},
    rank:{name:"Legendary",about:"Raise any hero to Legendary rank"},
    team:{name:"Full Druzhina",about:"Gather all 9 bogatyrs"},
    streak:{name:"Faithful",about:"Daily quest streak: 7 days in a row"},
    cur1:{name:"Cursed",about:"Win a chapter on Curse I or higher"},
    cur5:{name:"Stronger than Likho",about:"Win a chapter on Curse V"},
    wk1:{name:"Trialist",about:"Complete the Weekly Trial (1 min or longer)"},
    wk4:{name:"Regular",about:"Complete Weekly Trials in 4 different weeks"},
    best:{name:"Monster Expert",about:"Unlock every monster and boss in the Bestiary"}
  },
  TUT:{
    move:{t:"Drag across the screen to move. Attacks are automatic!"},
    gem:{t:"Collect gems 💎: they give you XP."},
    card:{t:"Pick a skill: a new weapon or an upgrade."}
  },
  TUT_EV:{
    elite:"An elite! Defeat it and it drops a chest.",
    chest:"A chest! Gifts are handed out automatically.",
    end:"Survive until 5:00 and the chapter boss arrives!"
  },
  WEEKLY:{
    bow:{name:"Archer Week",about:"Only Alyosha's bow, but arrows fly more often. Other weapons stay in the shed."},
    fast:{name:"Monsters in a Hurry",about:"All monsters run 1.5× faster. A third more gold."},
    fast2:{name:"Hungry Week",about:"No pirozhki, no living water: no healing at all. But +3 armor."},
    gold:{name:"All or Nothing",about:"Gold ×2, but only one life: no wise woman, no revive for an ad."},
    giant:{name:"Giants",about:"Monsters are twice as big and three times as tough, but give double XP."},
    horde:{name:"Horde upon Horde",about:"Twice as many monsters, but they're flimsy: one sneeze knocks them over."},
    glass:{name:"Glass Bogatyr",about:"Your hero has half health, but ×1.7 damage."},
    kolo:{name:"Kolobok Week",about:"Only koloboks, but two at once, and they roll longer."}
  },
  LORE:{
    muh:"A poisonous mushroom with a poisonous temper. Walks slowly, takes offense quickly. Keep out of the soup!",
    bat:"A gossiping bat. Sleeps upside down all day, bites everyone at night.",
    wolf:"A grey wolf, but not the one from the tales who carries princes around. This one just snaps.",
    lesh:"Leshy, the forest spirit. Leads travelers in circles, and long ago forgot where he lives himself.",
    piy:"A swamp leech. Small, fast and very clingy, like an auntie at a family party.",
    kik:"Kikimora, the swamp hag. Giggles, tickles, hides your bast shoes. Her sense of humor is… special.",
    ogon:"A will-o'-wisp. Glows prettily, lures you into the bog, shoots when you're not looking.",
    vod:"Vodyanoy, the water spirit. Pot-bellied, soggy and always grumpy: someone swam in his pond again.",
    voron:"A prophetic raven. Foretells trouble, then causes it himself. Caw!",
    skel:"A skeleton from a burial mound. His bones ache before rain, but he never skips a fight.",
    upyr:"Upyr, the pale Slavic vampire. Looking for someone to bite, turns his nose up at garlic.",
    idol:"Idolishche, the pagan idol brute. Big, heavy, with a club. Thinks slowly, hits hard.",
    prizr:"A ghost of Koschei's Kingdom. Says \"Ooo-ooo\" and thinks that's very scary.",
    koldun:"A sorcerer who flunked his studies. Mixes up his spells, but his fireballs hit the mark.",
    rycar:"A bone knight. Has served Koschei for a thousand years and still hasn't had a vacation.",
    kot:"Baba Yaga's black cat. Crossing your path means bad luck. For you.",
    wolf_i:"An ice wolf. Howls from the cold. Somebody get him a fur coat.",
    ledyan:"An ice spirit. Blows so hard your beard turns to frost.",
    snow:"A hooligan snowman. Throws snowballs. Don't touch his carrot: it's sacred.",
    shatun:"A bear woken up in the middle of winter. He will never forgive you for that.",
    ryba:"A toothy fish. A smile from ear to ear, and it's all teeth.",
    rak:"A hermit crab. Walks backwards, pinches forwards.",
    rusalka:"Rusalka, the river mermaid. Sings, invites you for a swim, splashes shells. Decline politely but firmly.",
    vod_s:"The sea Vodyanoy, big brother of the swamp one. Saltier and twice as nasty.",
    chert:"An imp. Horns, hooves, matches. Favorite pastime: setting your heels on fire.",
    ognev:"A fire sprite. A real hothead, literally. Spits sparks.",
    skel_f:"A fire skeleton. Burns at work, but never burns out. A true workaholic.",
    idol_f:"A fire idol. Just like a regular Idolishche, only preheated.",
    solo:"Nightingale the Robber, the bandit of Russian epics. One whistle knocks you off your feet, then he calls the wolves. Nests on nine oaks, pays tax on one.",
    yaga:"Baba Yaga, the bony-legged witch. Flies in a mortar, sweeps her tracks with a broom, sets cats on you. Loves guests, especially roasted.",
    gory:"Zmey Gorynych, the three-headed dragon. All three heads argue over who gets to breathe fire. While they argue, they roast.",
    kosh:"Koschei the Deathless. His death is hidden in a needle, inside an egg. Pines over gold, laughs at you. Thin as a coat hanger, yet tough enough for a whole fairy tale.",
    egg:"THE egg. Koschei pretends it has nothing whatsoever to do with him.",
    karach:"Karachun, the anti-Santa winter demon. Brings no presents, but hands out icicles to everyone, free of charge.",
    morcar:"The Sea Tsar. Waves his trident, drives the waves, sends crabs into battle. Loves gusli music, but probably not yours.",
    tugar:"Tugarin Zmey, a winged fire-breathing dragon-warrior. Very full of himself. Threatens to eat you, but he'll choke.",
    liho:"Likho One-Eye, the embodiment of bad luck. One eye, but what an eye: its gaze is a burning beam. Let sleeping Likho lie!"
  }
};
(function(){const T={HEROES,RANKS,WEAPONS,PASSIVES,EN,FINDS,CH,FORGE,BLD,PH,QUESTS,SKINS,CURSES,ACH,TUT,TUT_EV,WEEKLY,LORE};
  for(const n in I18N_EN)trData(T[n],I18N_EN[n]);applyLang();
  if(/[?&]i18ncheck/.test(location.search))console.log('i18ncheck',i18nCheck(Object.assign({PAY_ITEMS},T)));})();
