'use strict';
/* ================= English: наложение на таблицы data.js и pay.js (см. js/lang.js) =================
   Ключи и порядок — как в русских таблицах. Поменял/добавил русский текст в data.js — поправь и здесь.
   Имена из сказок — как в английской версии «Богатыря»: Baba Yaga, Koschei the Deathless, Zmey Gorynych, Nightingale the Robber… */
langReg(TW,{
  arch:{n:'Archers',short:'Archers',about:'They shoot often and hit sometimes. They can hit flyers too.',
    br:[{n:'Hawkeye',sh:'Hawkeye',about:'Long range, big hurt. Sometimes right in the eye: double damage.'},
        {n:'Arrow Rain',sh:'Rain',about:'Three targets at once. Arrows in the sky, panic on the ground.'}]},
  pushka:{n:'Cannoneers',short:'Cannon',about:'Boom — and the crowd is gone. They can’t see flyers: cannoneers watch their feet.',
    br:[{n:'Tsar Cannon',sh:'Tsar',about:'Huge ball, huge boom, stuns everyone. And this one actually fires!'},
        {n:'Pie Mortar',sh:'Pies',about:'Lobs hot cabbage pies. The ground burns, the monsters get scorched.'}]},
  izba:{n:'Auntie Yaga’s Hut',short:'Yaga’s Hut',about:'Auntie brews a potion: the puddle poisons and slows. Can’t reach flyers — the broom is in for repairs.',
    br:[{n:'Toadstool Brew',sh:'Poison',about:'Poison three times nastier, and it eats through armor. Do not drink! Not even on a dare.'},
        {n:'Jelly Banks',sh:'Jelly',about:'Thick berry jelly: enemies barely crawl, and sometimes get stuck for good.'}]},
  mag:{n:'Hermit Sorcerer',short:'Sorcerer',about:'Lightning jumps from enemy to enemy and ignores armor.',
    br:[{n:'Perun’s Magus',sh:'Magus',about:'Lightning bounces through five. Loud, bright, and no electricity bill.'},
        {n:'Frogmaker',sh:'Frogs',about:'Sometimes turns a monster into a frog. Frogs don’t storm cities.'}]},
  dub:{n:'Giant Oak',short:'Oak',about:'Roots from underground — whack! Stuns everyone nearby. An oak, but no blockhead.',
    br:[{n:'Ancient Oak',sh:'Ancient',about:'Wider roots, harder hits, longer stun. The wisdom of ages!'},
        {n:'Lukomorye Oak',sh:'Wise Cat',about:'A learned cat lives on this oak: its tales put monsters to sleep and slow them. +50% coins for monsters nearby.'}]}
});
langReg(LEAD,{n:{lesh:'Father Leshy'},about:'Master of the thicket: tough and heals on the move. Knock him down!',
  say:['Who’s making noise in MY forest?!','Oh, I’ll get you!','Out of my way, shoo!']});
langReg(SPELLS,{thunder:{n:'Perun’s Thunder',about:'Tap and pick a spot — lightning strikes there.'},
  cat:{n:'Bayun the Cat',about:'The cat sings a lullaby: every monster falls asleep.'}});
langReg(EN,{
  muh:{n:'Toadstool',about:'Slow and stubborn. Only poisonous if you eat it — so don’t.'},
  wolf:{n:'Grey Wolf',about:'Runs fast. Claims he’s taking pies to Grandma.'},
  bat:{n:'Bat',about:'It flies! Cannon, hut and oak can’t reach it — only arrows and magic.'},
  lesh:{n:'Leshy',about:'Pot-bellied and green. Heals on the go — tough as old boots.'},
  piy:{n:'Leech',about:'Small and quick, travels in crowds. Not scary one at a time.'},
  kik:{n:'Kikimora',about:'Giggles and hops ahead, cutting corners.'},
  ogon:{n:'Will-o’-Wisp',about:'A flying swamp light. Arrows barely touch it, the sorcerer does just fine.'},
  vod:{n:'Vodyanoy',about:'Wet and grumpy. His coat of pond slime soaks up a quarter of the damage.'},
  voron:{n:'Raven',about:'Caws in your ear and flies straight to the city. Shoot it down!'},
  skel:{n:'Skeleton',about:'Tough bones: arrows bounce off. Use magic and poison.'},
  upyr:{n:'Upyr',about:'Pale, hungry and heals fast.'},
  idol:{n:'Idolishche',about:'Huge and armored. Eats for three, stomps for four.'},
  prizr:{n:'Ghost',about:'Arrows fly right through. The sorcerer hits it at full strength.'},
  koldun:{n:'Black Sorcerer',about:'Heals his neighbors. Magic works on him at half strength.'},
  rycar:{n:'Bone Knight',about:'Armored head to toe. Arrows tickle, lightning fits just right.'},
  kot:{n:'Black Cat',about:'Crosses your road. Bad luck — for you.'},
  wolf_i:{n:'Ice Wolf',about:'Fast and cold. Wet nose, sharp teeth.'},
  ledyan:{n:'Ice Spirit',about:'A flying draft. Half the arrows miss.'},
  snow:{n:'Snowman',about:'Break him and he falls apart into two snowballs. Who even built him?!'},
  snowb:{n:'Snowball',about:'Small, round and easily offended.'},
  shatun:{n:'Grumpy Bear',about:'Woken up in the middle of winter — now he’s angry. Runs twice as fast when hurt.'},
  ryba:{n:'Toothy Fish',about:'Swims along the road like it’s a river. More teeth than brains.'},
  rak:{n:'Hermit Crab',about:'Walks sideways, but keeps coming. Its shell stops arrows and cannonballs.'},
  rusalka:{n:'Rusalka',about:'She sings — and her neighbors heal. Cover your ears!'},
  vod_s:{n:'Sea Vodyanoy',about:'A vodyanoy, but from the sea — and twice as hefty.'},
  chert:{n:'Imp',about:'Fast, cheeky, with a pitchfork. A wagging tail means mischief.'},
  ognev:{n:'Fire Sprite',about:'Flying fire. Hisses at arrows.'},
  skel_f:{n:'Fire Skeleton',about:'A skeleton, but hot. Bones in armor made of soot.'},
  idol_f:{n:'Fire Idol',about:'A red-hot Idolishche. Do not hug.'},
  solo:{n:'Nightingale the Robber',about:'One whistle — and nearby outposts go deaf for a while.'},
  yaga:{n:'Baba Yaga Bone-Leg',about:'Auntie Yaga’s evil sister. Dashes about in her mortar and calls her cats.'},
  gory:{n:'Zmey Gorynych',about:'Three heads — three fireballs: he burns outposts and they go quiet.'},
  kosh:{n:'Koschei the Deathless',about:'Deathless while his egg is whole. Break the egg — with your finger or your outposts!'},
  karach:{n:'Karachun',about:'Breathes frost — nearby outposts shoot half as often.'},
  morcar:{n:'The Sea Tsar',about:'Calls the tide: every monster nearby heals. And he brings crabs.'},
  tugar:{n:'Tugarin Zmey',about:'Hides behind a fiery shield: while it burns, he can’t be hurt.'},
  liho:{n:'Likho One-Eye',about:'One look at an outpost — and it falls asleep. Don’t look Likho in the eye!'},
  egg:{n:'Egg with the Needle',about:'Inside is a needle. At the needle’s tip — Koschei’s death.'}
});
langReg(BOSS_SAY,{
  solo:['Wheee-oo! Mind your ears!','One whistle and you’re all deaf!','Your money or your life!'],
  yaga:['Fee-fi-fo, I smell a hero!','Sister dear, whose side are you on?!','Kitties, charge!'],
  gory:['There are three of us — and we’re all hungry!','Who built all these outposts?','Here comes a big breath!'],
  kosh:['I’m deathless, you know!','I gloat over gold and laugh at you!','Hands off the egg!'],
  karach:['Freeze and don’t complain!','Winter is here. Without warning.','Ooh, fresh!'],
  morcar:['Tide, to me!','Crabs, attack! Sideways!','Where’s my trident?.. Ah, here.'],
  tugar:['My shield burns — I don’t!','Tugarin’s coming — everything burns!','Too hot for you? I’m fine.'],
  liho:['One look — and you’ll sleep!','Let sleeping Likho lie. It wakes up on its own.','I see everything with one eye!']
});
langReg(SAY_SPAWN,['We just want to ask something!','We’re here for the pies!','Which way to the city?','Hurraaah!','There are lots of us!','What did we do?','Don’t shoot, we’re peaceful! Mostly.','Today is our day!','Last one there is a toadstool!','Hey, you on the outpost!']);
langReg(SAY_LEAK,['We made it!','Hooray, the city!','Where are the pies?','I’m first!','Hee-hee!']);
langReg(SAY_HIT,['Ow!','Oof!','Not fair!','Mommy!','That hurts!']);
langReg(WAVE_NAMES,{
  muh:['Mushroom Shower','Toadstool March','Toadstools on a Stroll'],wolf:['Wolf Pack','Grey and Toothy','“Off to Grandma’s”'],
  bat:['Bats Overhead','Night Flight'],lesh:['The Leshies Arrive','Green Giants'],
  piy:['Leech Swim','Biting Small Fry'],kik:['The Giggle Squad','Hopping Kikimoras'],ogon:['Swamp Lights','Firefly Pests'],vod:['Vodyanoys Emerge','Bloop-bloop'],
  voron:['Raven Cloud','Caw-caw-caw'],skel:['Rattling Bones','Skeletons in the Closet… er, Field'],upyr:['Hungry Upyrs','Pale and Peckish'],idol:['The Foul Idolishche','Stomp-stomp-STOMP'],
  prizr:['Ghosts','A Draft from Beyond'],koldun:['The Coven','Black Healers'],rycar:['Bone Knights','Iron Clatter'],kot:['Cat Concert'],
  wolf_i:['Ice Wolves','Frosty Fangs'],ledyan:['Blizzard with Eyes','Ice Spirits'],snow:['Snowmen Advance','Snowball Effect'],shatun:['Bears Don’t Sleep','A Bear Hug'],
  ryba:['School of Fish','Toothy Small Fry'],rak:['Crabs Sidling Forward','Shell Parade'],rusalka:['Rusalka Choir','Songs with Tails'],vod_s:['Sea Brutes'],
  chert:['Dancing Imps','Horned Small Fry'],ognev:['Fire Sprites Incoming','Sizzle-sizzle'],skel_f:['Hot Bones'],idol_f:['Idol on Fire','Red-Hot Stomping'],
  mix:['All-Out Assault','The Whole Gang','The Last Push','Monster Medley']
});
langReg(CH,[
  {name:'Deep Dark Forest',sub:'Where the leshy roams and wolves howl',
    levels:['Forest Edge','Mushroom Glade','Wolf Trail','Leshy Thicket','Windfall','Nightingale’s Lair'],
    intro:['Monsters are coming out of the forest! Put archers by the road — let them shoot instead of picking their noses.',
      'The toadstools march in rows. The cannoneers will settle this mushroom matter. Only the cannon can’t see bats — archers take those!',
      'Auntie Yaga agreed to help. For a pension and firewood. Her potion poisons and slows. And if it gets really tough — call Perun’s Thunder!',
      'Leshies are thick-skinned and heal on the move. And Bayun the Cat has joined us — one song and every monster falls asleep.',
      'A hermit sorcerer came to the outpost. His lightning never misses — even flyers.',
      'Nightingale the Robber! One whistle and nearby outposts go deaf. Hold on, lads!']},
  {name:'Deadly Swamp',sub:'Kikimoras giggle, the vodyanoy gurgles',
    levels:['Tussocks','Log Road','Frog Pond','Foggy Mire','Kikimora’s Pool','Bone-Leg’s Hut'],
    intro:['A swamp. Even the mosquitoes have beards here. But the old Giant Oak woke up — and it’s itching for a fight!',
      'Kikimoras hop ahead. Build outposts near the end of the road too, not just the start.',
      'Level 3 outposts can now train into masters. Two branches — choose wisely!',
      'Fog. Wisps fly around and arrows barely touch them. The sorcerer is our friend.',
      'Vodyanoys are huge and covered in slime. Cannon and poison work best.',
      'Baba Yaga Bone-Leg! Auntie says: “My sister has gone completely off the rails.” Let’s teach her a lesson!']},
  {name:'Wild Steppe',sub:'Ravens circle over the burial mounds',
    levels:['Burial Mounds','Feather Grass','Raven Ford','Dry Ravine','Stone Babushka','Kalinov Bridge'],
    intro:['The Wild Steppe. Wind, feather grass and ravens. Ravens fly — more archers!',
      'Skeletons in armor made of their own bones. Arrows bounce off — call the sorcerer and Yaga.',
      'Upyrs heal fast. Hit them all together so they don’t have time.',
      'The foul Idolishche! Big and armored. The Tsar Cannon has been dying to meet him.',
      'There’s a stone babushka statue here. They say she watches who builds best. Don’t embarrass yourself.',
      'Kalinov Bridge over the Smorodina River. Zmey Gorynych is flying in — he burns outposts!']},
  {name:'Koschei’s Kingdom',sub:'Gloating over gold, glowing in the dark',
    levels:['Graveyard','Misty Wood','Bone Bridge','Black Pinewood','Chest of Gold','Koschei’s Castle'],
    intro:['Koschei’s Kingdom. Dark, damp, and ghosts. Arrows and cannonballs don’t touch them — you need the sorcerer.',
      'The skeletons are back. Looks like they live here.',
      'Black sorcerers heal their own. Take them out first!',
      'Bone knights in plate armor. Lightning is just their size.',
      'A chest of gold! Koschei gloats over it. We won’t — we’ll shoot.',
      'Koschei the Deathless. Deathless while the egg is whole! When it appears — tap it!']},
  {name:'Frost Mountains',sub:'Snowmen throw, bears don’t sleep',
    levels:['Mountain Pass','Icy Brook','Snowman Hill','Bear Den','Ice Cave','Karachun’s Throne'],
    intro:['The Frost Mountains. Brrr! Archers, stop chattering your teeth — you keep missing.',
      'Ice spirits fly and blow drafts. Sorcerer, help us out.',
      'Snowmen! Break one and it scatters into snowballs. Use splash damage.',
      'A grumpy bear. Hurt means furious. Build Jelly Banks and let him get stuck.',
      'The Ice Cave. There’s an echo here. Echo. Echo…',
      'Karachun! He breathes frost — nearby outposts shoot half as often. Spread out!']},
  {name:'Sea Kingdom',sub:'Crabs back off, rusalkas sing',
    levels:['Shallows','Coral Garden','Sunken Longboat','Rusalka Cove','Crab Hole','Sea Palace'],
    intro:['The Sea Kingdom. How do we breathe underwater? Don’t ask, it’s a fairy tale.',
      'Crabs in shells. Cannonballs bounce off, but poison and lightning get through.',
      'A sunken longboat. They say there’s treasure here. Fight first, dig later.',
      'Rusalkas sing — monsters heal. Take out the singers first!',
      'The Crab Hole. Crabs walk sideways… yet somehow toward us.',
      'The Sea Tsar! He calls the tide — every monster nearby heals. Hit fast!']},
  {name:'Land of Fire',sub:'Imps dance, the ground burns',
    levels:['Ashes','River of Fire','Devil’s Forge','Sulfur Springs','Volcano','Tugarin’s Nest'],
    intro:['The Land of Fire. It’s hot here. Very. Auntie Yaga brews her potion right on the ground.',
      'Fire sprites fly. Archers, sorcerer — to battle!',
      'The Devil’s Forge. Imps forge mischief here. We forge victory.',
      'Sulfur Springs. Smells like… well, like imps.',
      'A volcano. Stay away from the edge, commander.',
      'Tugarin Zmey! He hides behind a fiery shield. When the shield goes out — everybody hit him!']},
  {name:'Thrice-Nine Kingdom',sub:'Likho never sleeps — one eye is always open',
    levels:['Jelly Banks','Milk River','Legless Hut','Lukomorye','The Abyss','Likho’s Lair'],
    intro:['The Thrice-Nine Kingdom. Nothing here is normal. Jelly flows, milk babbles.',
      'The Milk River. Don’t drink — monsters washed their feet in it.',
      'A hut without legs. Auntie Yaga says it’s her ex.',
      'Lukomorye! The learned cat says hi. The Lukomorye Oak is especially good here.',
      'The Abyss. Whoever falls doesn’t pass. Too bad monsters don’t fall.',
      'Likho One-Eye. One look — and an outpost falls asleep. The last battle, commander. Don’t let us down!']}
]);
langReg(FORGE_T,{dmg1:{n:'Tempering',d:'+10% damage'},rng:{n:'Taller Tower',d:'+10% range'},dmg2:{n:'Master Crafters',d:'+15% damage'},
  cheap:{n:'Guild',d:'−10% build and upgrade cost'}});
langReg(FORGE_SP,{arch:{n:'Marksmanship',d:'15% chance of double damage'},pushka:{n:'Stronger Powder',d:'+25% blast radius'},
  izba:{n:'Thick Brew',d:'the puddle lasts 1.5 s longer'},mag:{n:'Chain Lightning',d:'+1 lightning target'},dub:{n:'Strong Roots',d:'stun +0.3 s'}});
langReg(FORGE_EXTRA,[
  {n:'Perun’s Thunder',d:['+35% lightning damage','+35% damage and a wider strike','+35% damage, cooldown −10 s']},
  {n:'Bayun the Cat',d:['sleep +0.6 s','sleep +0.6 s','cooldown −15 s']},
  {n:'Sturdy Gates',d:['+3 lives in every battle','another +3 lives']},
  {n:'Thrift',d:['+40 coins at the start of a battle','another +40','another +40']}]);
langReg(BLD,{
  mint:{name:'Toll House',about:'The treasury saves up gold while you’re away: +10 per hour per level'},
  barn:{name:'Granary',about:'The treasury holds 2 more hours'},
  fair:{name:'Fair',about:'+25 coins at the start of every battle'},
  smith:{name:'Smiths’ Quarter',about:'Outposts and upgrades 4% cheaper'},
  range:{name:'Shooting Range',about:'All outposts hit 4% harder'},
  herb:{name:'Herbalist’s Hut',about:'Spells recharge 8% faster'},
  wall:{name:'Palisade',about:'+1 life in every battle'}});
langReg(SKINS,{spring:{n:'Spring',about:'flowers on the roofs'},fair:{n:'Fairground',about:'a garland of bunting'},
  winter:{n:'Winter',about:'snow caps and icicles'},gold:{n:'Gilded',about:'gilding and sparkles'}});
langReg(DECO,{well:{n:'Sweep Well'},flags:{n:'Fair Bunting'},kot:{n:'Bayun on the Fence'},swing:{n:'Swing'},carousel:{n:'Carousel'},fire:{n:'Midsummer Bonfire'}});
langReg(SKIN_FB,{n:'Firebird',about:'fiery feathers'});
langReg(QUESTS,{win:{n:'Win battles'},star3:{n:'Clear levels with three stars'},build:{n:'Build outposts'},kills:{n:'Defeat monsters'},
  spells:{n:'Cast spells'},ups:{n:'Upgrade outposts'},siege:{n:'Hold off siege waves'}});
langReg(AIMS,{first:{n:'First',s:'first',d:'whoever is closest to the gate'},strong:{n:'Strongest',s:'strong',d:'whoever has the most health'},
  near:{n:'Nearest',s:'nearest',d:'whoever is closest to the outpost'},fly:{n:'Flyers',s:'flyers',d:'flyers first, then the first one'},crowd:{n:'Crowd',s:'crowd',d:'wherever the monsters are thickest'}});
langReg(DIFF,[{n:'Fairy Tale',p:'Fairy Tale',d:'Monsters are a quarter weaker. For relaxing and for young commanders. Same stars.'},
  {n:'True Tale',p:'True Tale',d:'Normal monster strength — as intended.'},
  {n:'Heroic',p:'Heroic',d:'Monsters are a fifth tougher. Victory earns a crown 👑 on the level.'}]);
langReg(DCH_RULES,{blitz:{n:'Blitz',d:'Only 6 seconds between waves, but a third more coins at the start.'},
  lives:{n:'Five Lives',d:'Only 5 lives — let almost no one into the city.'},
  noarch:{n:'No Archers',d:'The archers went to the fair. Only the sorcerer can hit flyers.'},
  nospell:{n:'No Spells',d:'Perun and Bayun the Cat are resting — outposts only. But a quarter more coins at the start.'},
  fast:{n:'Monsters in a Hurry',d:'Monsters run a fifth faster, but pay a fifth more coins.'},
  poor:{n:'Stingy Commander',d:'A fifth fewer coins at the start. Count every one!'}});
langReg(LORE,{
  muh:'A poisonous mushroom with a poisonous temper. Walks slowly, takes offense quickly. Do not put in soup!',
  wolf:'A grey wolf, but not the one who gives princes a ride. This one just snaps his teeth.',
  bat:'A gossiping bat. Sleeps upside down all day, bites everyone at night.',
  lesh:'Lord of the forest. Leads travelers in circles and has long forgotten where he lives himself.',
  piy:'A swamp leech. Small, fast and very clingy — like an aunt at a family party.',
  kik:'A swamp kikimora. Giggles, tickles, hides your bast shoes. Her sense of humor is… special.',
  ogon:'A wandering light. Shines prettily and leads you straight into the bog.',
  vod:'The vodyanoy. Pot-bellied, wet and always grumpy: someone went swimming in his pond again.',
  voron:'A prophetic raven. Predicts disaster — and then arranges it himself. Caw!',
  skel:'A skeleton from a burial mound. His bones ache before rain, but he never misses a fight.',
  upyr:'A pale upyr. Looking for someone to bite, and turns up his nose at garlic.',
  idol:'The foul Idolishche. Big, heavy, with a club. Thinks slowly, stomps loudly.',
  prizr:'A ghost of Koschei’s kingdom. Says “Boo-oo-oo” and thinks it’s terrifying.',
  koldun:'A sorcerer who dropped out of school. Mixes up his spells, but learned to heal his friends.',
  rycar:'A bone knight. Has served Koschei for a thousand years and still hasn’t had a vacation.',
  kot:'Baba Yaga’s black cat. Crosses your road — trouble ahead. For you.',
  wolf_i:'An ice wolf. Howls from the cold — someone give him a fur coat. Nobody will.',
  ledyan:'An ice spirit. Blows so hard your beard frosts over.',
  snow:'A hooligan snowman. Don’t touch the carrot — it’s sacred.',
  snowb:'A little piece of snowman. Small, round and very touchy.',
  shatun:'A grumpy bear. Someone woke him up mid-winter, and he will never forgive it.',
  ryba:'A toothy fish. A smile from ear to ear — and it’s all teeth.',
  rak:'A hermit crab. Walks sideways, but pinches straight ahead.',
  rusalka:'A rusalka. Sings, invites you for a swim, splashes with seashells. Decline politely but firmly.',
  vod_s:'The sea vodyanoy — the swamp one’s big brother. Salty and twice as nasty.',
  chert:'An imp. Little horns, little hooves, matches. Favorite pastime — setting your heels on fire.',
  ognev:'A fire sprite. A hothead — literally. Spits sparks.',
  skel_f:'A fire skeleton. Burns at work but never burns out. A workaholic.',
  idol_f:'A fire idol. Like a regular Idolishche, but heated.',
  solo:'Nightingale the Robber. One whistle and outposts go deaf. Sits on nine oaks, pays tax on one.',
  yaga:'Baba Yaga Bone-Leg. Flies in a mortar, sweeps her tracks with a broom, sets her cats on you.',
  gory:'Zmey Gorynych. Three heads, all arguing over whose turn it is to breathe fire. While they argue — they roast.',
  kosh:'Koschei the Deathless. Gloats over gold, laughs at you. Skinny as a coat hanger, yet impossible to kill.',
  egg:'THE egg. Koschei pretends it has absolutely nothing to do with him.',
  karach:'Karachun — Father Frost in reverse. Brings no presents, but hands out icicles — to everyone, free of charge.',
  morcar:'The Sea Tsar. Waves his trident, drives the waves, sends crabs to battle. Loves the gusli — though probably not yours.',
  tugar:'Tugarin Zmey. Winged, fire-breathing and very full of himself. Threatens to eat you — and chokes.',
  liho:'Likho One-Eye. Only one eye, but what an eye: one look and the outpost falls asleep. Let sleeping Likho lie!'
});
langReg(ACH,{
  k500:{n:'First Blood',d:'Defeat 500 monsters'},k5k:{n:'Monster Menace',d:'Defeat 5,000 monsters'},k50k:{n:'Outpost Legend',d:'Defeat 50,000 monsters'},
  b_solo:{n:'Nightingale in a Cage',d:'Defeat: Nightingale the Robber'},b_yaga:{n:'Not into the Oven!',d:'Defeat: Baba Yaga Bone-Leg'},
  b_gory:{n:'Three Heads Down',d:'Defeat: Zmey Gorynych'},b_kosh:{n:'The Needle Is Broken',d:'Defeat: Koschei the Deathless'},
  b_karach:{n:'The Thaw',d:'Defeat: Karachun'},b_morcar:{n:'Lord of the Waters',d:'Defeat: The Sea Tsar'},
  b_tugar:{n:'Firefighter',d:'Defeat: Tugarin Zmey'},b_liho:{n:'Let Likho Lie',d:'Defeat: Likho One-Eye'},
  ch8:{n:'Liberator of Rus',d:'Free all 8 chapters'},st72:{n:'Sharp Commander',d:'Collect 72 stars'},st144:{n:'All the Stars',d:'Three stars on all 48 levels'},
  cr1:{n:'Heroic Strength',d:'Beat a level on “Heroic”'},cr12:{n:'Crown after Crown',d:'Collect 12 crowns'},cr48:{n:'Tsar Commander',d:'Collect crowns on all 48 levels'},
  end20:{n:'Steadfast',d:'Hold off 20 siege waves'},end40:{n:'Unbreakable',d:'Hold off 40 siege waves'},
  wk1:{n:'Terror of the Week',d:'Defeat the Boss of the Week'},wk4:{n:'Regular',d:'Defeat the Bosses of 4 different weeks'},
  dch1:{n:'Challenger',d:'Complete a daily challenge'},dch7:{n:'Seasoned Challenger',d:'Complete 7 daily challenges'},
  tw100:{n:'One for All',d:'One outpost defeated 100 monsters in a battle'},vil:{n:'A Village of Your Own',d:'Build all 7 village buildings'},
  frg:{n:'Master of the Forge',d:'Forge every upgrade of one outpost'},book:{n:'Monster Expert',d:'Discover every monster and boss in the book'}});
langReg(TIPS,[
  'Tap an outpost to upgrade or sell it. Selling returns 70% of the coins.',
  'The “Wave early” button pays coins for courage. Courage is well paid here.',
  'Only archers and the sorcerer hit flyers. Watch for the little wings icon.',
  'Armored enemies are best hit with magic and Yaga’s poison: armor doesn’t help them.',
  'A bend in the road is the best spot for a cannon or an oak: enemies bunch up there.',
  'Stars from battles are spent in the forge. The forge can be reset for free — experiment!',
  'The treasury saves up gold while you rest. The commander rests too. Sometimes.',
  'Three stars — if no more than two enemies broke into the city.',
  'Bayun the Cat puts everyone to sleep. Bosses only briefly: they snore, but wake up fast.',
  'Speed ×2 is for the brave. Pause is for the wise.']);
// покупки: английские названия — поле en в PAY_ITEMS (js/pay.js)
{const o={};for(const id in PAY_ITEMS)if(PAY_ITEMS[id].en)o[id]=PAY_ITEMS[id].en;langReg(PAY_ITEMS,o);}
langDom();
